config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  get 'home/show'

  root to: "home#index"

	resources :search

	match 'slides/:requestid/:ID/edit' => 'slides#edit', :via => :get, as: 'edit_slide_info'
	match 'slides/update' => 'slides#update', :via => :post
	match 'slides/delete' => 'slides#delete', :via => :post

	resources :slides

  mount Sidekiq::Web, at: "/sidekiq"
end

app/models/search.rb
class Search < ActiveRecord::Base
# パラメータ
# requestid,userid,q,lang,state,request_date,last_update_date
# ここで状態も管理
# state(0:requested,1:accepted,2:processing,3:complete,-1:abort)
# 依頼方法は
# s = Search.create(userid,q,lang);
# この後、sidekiqでのトリガー
#
# 状態の確認

end

app/models/slide.rb
class Slide < ActiveRecord::Base
# パラメータ
#  要求メタデータ
#  requestid
#  スライド情報
#  ID,Title,Description,Status,URL,ThumbnailURL,ThumbnailSize,ThumbnailSmallURL,Embed,Created,Updated,Format,DownloadURL,SlideshowType

end

app/models/slide_source.rb
require 'active_resource'

class SlideSource < ActiveResource::Base
	class Connection < ActiveResource::Connection
		private
		def http()
		 	http=super;
			http.set_debug_output($stderr);
			http
		end
	end
	class Format
		def extension()
			'';
		end
		def mime_type()
			'text/xml';
		end
		def encode(hash,options={})
			hash.to_xml(options);
		end
		def decode(xml)
			data = Hash.from_xml(xml);
			data.is_a?(Hash) && data.keys.size == 1 ? data.values.first : data ;
		end
	end

	self.site   = 'https://www.slideshare.net';
	self.format = Format.new;

	class << self
		def connection(refresh=false)
			if defined?(@connection)
				@connection          = Connection.new(site,format) if refresh || @connection.nil?
				@connection.user     = user if user;
				@connection.password = user if password;
				@connection.timeout  = timeout if timeout ;
				@connection
			else
				superclass.connection;
			end
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	#skip_filter :index , :only
  before_action :authenticate_user!, except: :index

  def index
		redirect_to :action => 'show' if user_signed_in?
  end

  def show
		p current_user
  end
end

app/controllers/search_controller.rb
# coding: utf-8

# 検索要求を管理するcontroller
class SearchController < ApplicationController

  #include models::Search
  #include Search
  #include Sidekiq:Worker
  #sidekiq_options queue: :slideshare_query
  before_action :authenticate_user!

	def index
    @req = Search.where(users_id: current_user.id);
	end

	def new
		@req = Search.new
	end

	def create
		# いったん、ユーザーIDは固定で。
		exec(current_user.id, params[:req][:q], params[:req][:lang] )
    @req = Search.where(users_id: current_user.id);
	end

	def exec(userid,q,lang)
		# 検索依頼
		r = Search.new
		r.users_id = userid
		r.q = q
		r.lang = lang
		r.state = 0
		r.request_date = Time.now
		r.save

		@req = r

		SlideshareWorker.perform_async( r.requestid )
		
	end

  def show
		# 認証系が機能していないので
    @req = Search.where(userid: current_user.id);
  end

#  def stat(uid,reqid)
#    # 要求状態確認
#    req = Search.where(requestid: reqid,userid: uid)
#    req
#  end

end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
	before_action :authenticate_user!

  def index
		@slides = mySlideList(current_user.id)
  end

  def show
		@slides = mySlideList(current_user.id)
  end

	def edit
		# 詳細表示アクション
		# exec(1, params[:req][:ID], params[:req][:requestid] )
		@slide = mySlide(current_user.id, params[:ID], params[:requestid] )
		p @slide
	end

	def	update
		# 変更アクション
		id = params[:f][:ID];
		rid = params[:f][:requestid];
		ti = params[:f][:Title];
		ds = params[:f][:Description] ;
		Slide.where(userid: current_user.id, ID: id, requestid: rid ).update_all(Title: ti, Description: ds ) ;
		redirect_to :action => 'index', :notice => '更新しました'
	end

	def delete
		# 削除アクション
		mySlideDelete(current_user.id, params[:f][:ID], params[:f][:requestid] )
		redirect_to :action => 'index', :notice => '削除しました'
	end

	protected

	def mySlideList(userID)
		list = Slide.where(userid: userID);
		list
	end

	def mySlide(userID,slideID,requestID)
		# いったん全部
		return Slide.where(userid: userID,ID: slideID, requestid: requestID).first;
	end

	def mySlideDelete(userID,slideID,requestID)
		Slide.where(userid: userID, ID: slideID, requestid: requestID).delete_all;
	end

end

app/controllers/users_controller.rb
class HomeController < ApplicationController

	#skip_filter :index , :only
	#before_filter :authorize, :only => [:show]

  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_client_helper.rb
module SearchClientHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>

<a href="/users/sign_up">user signup</a>
<br/>
<a href="/sidekiq">sidekiq monitor</a>

app/views/home/show.html.erb
<h1>Home#index</h1>

<a href="/search">new search request</a>
<br/>
<a href="/slides">slides</a>
<br/>
<a href="/sidekiq">sidekiq monitor</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
  <%= link_to "Home", :controller => "/home", :action => "index"  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> |
  <%= link_to "Home", :controller => "/home", :action => "index"  %>
<% end %>


<%= yield %>


</body>
</html>

app/views/search/index.html.erb
<h1>Home#show</h1>
<p>bookmark slides</p>

<table>
<tr>
<th>requestid</th>
<th>query</th>
<th>lang</th>
<th>state</th>
<th>processed/total</th>
<th>request_date</th>
<th>last_update_date</th>
</tr>
<% @req.each do |req| %>
<tr>
<th> <%= req.requestid %></th>
<th> <%= req.q %></th>
<th> <%= req.lang %></th>
<th> <%= req.state %></th>
<th> <%= req.process_count %> / <%= req.total_count %></th>
<th> <%= req.request_date %></th>
<th> <%= req.last_update_date %></th>
</tr>
<% end %>
</table>

<br />

<%= link_to 'new request', new_search_path %>

app/views/search/new.html.erb
<h1>new search request</h1>
<p>search slides</p>

<%= form_for :req, :url => {:action => 'create'} do |f| %>
<%= f.label :q, "検索キーワード" %>
<%= f.text_field :q %>
<%= f.label :lang %>
<%= f.text_field :lang %>
<%= f.submit "検索する" %>
<% end %>

app/views/search/show.html.erb
<h1>Home#show</h1>
<p>bookmark slides</p>

<table>
<tr>
<th>requestid</th>
<th>query</th>
<th>lang</th>
<th>state</th>
<th>processed/total</th>
<th>request_date</th>
<th>last_update_date</th>
</tr>
<% @req.each do |req| %>
<tr>
<th> <%= req.requestid %></th>
<th> <%= req.q %></th>
<th> <%= req.lang %></th>
<th> <%= req.state %></th>
<th> <%= req.process_count %> / <%= req.total_count %></th>
<th> <%= req.request_date %></th>
<th> <%= req.last_update_date %></th>
</tr>
<% end %>
</table>

<br />

<%= link_to 'new request', new_search_path %>

app/views/slides/create.html.erb
<h1>Home#show</h1>
<p>search slide queue</p>

<table>
<tr>
<th>requestid</th>
<th>query</th>
<th>lang</th>
<th>state</th>
<th>request_date</th>
<th>last_update_date</th>
</tr>
<% @req.each do |req| %>
<tr>
<th> <%= req.requestid %> </th>
<th> <%= req.q %> </th>
<th> <%= req.lang %> </th>
<th> <%= req.state %> </th>
<th> <%= req.request_date %> </th>
<th> <%= req.last_update_date %> </th>
</tr>
<% end %>
</table>

<br />

<%= link_to 'new request', new_search_path %>

app/views/slides/edit.html.erb
<h1>new search request</h1>
<p>search slides</p>

<%= form_for :slide, :url => {:action => 'update',:controller =>'slides' } do |f| %>
<input type="hidden" id="f_requestid" name="f[requestid]" value="<%= @slide.requestid %>" />
<input type="hidden" id="f_ID" name="f[ID]" value="<%= @slide.ID %>" />
<table>
	<tr><th>項目名</th><th>値</th></tr>
	<tr><th>タイトル</th><th><%= text_field :f, :Title %></th></tr>
	<tr><th>説明</th><th><%= text_field :f, :Description %></th></tr>
</table>
<%= f.submit "更新する" %>
<% end %>

<%= form_for :slide, :url => {:action => 'delete',:controller =>'slides' } do |f| %>
<input type="hidden" id="f_requestid" name="f[requestid]" value="<%= @slide.requestid %>" />
<input type="hidden" id="f_ID" name="f[ID]" value="<%= @slide.ID %>" />
<%= f.submit "削除する" %>
<% end %>

app/views/slides/index.html.erb
<h1>Sides#index</h1>
<p>slide list</p>

<table>
<tr>
<th>requestid</th>
<th>ID</th>
<th>Title</th>
<th>Description</th>
<th>Status</th>
<th>URL</th>
<th>DownloadURL</th>
</tr>
<% @slides.each do |s| %>
<tr>
<th> <%= s.requestid %></th>
<th> <%= s.ID %></th>
<th> <%= s.Title %></th>
<th> <%= s.Description %></th>
<th> <%= s.Status %></th>
<th> <%= s.URL %></th>
<th> <%= s.DownloadURL %></th>
</tr>
<% end %>
</table>

<br />

<%= link_to 'new request', new_search_path %>

app/views/slides/item.html.erb
<h1>SLIDE information</h1>
<p>slide details</p>

<%= form_for :req, :url => {:action => 'create'} do |f| %>
<%= f.label :q, "検索キーワード" %>
<%= f.text_field :q %>
<%= f.label :lang %>
<%= f.text_field :lang %>
<%= f.submit "検索する" %>
<% end %>

<h1>Sides#index</h1>
<p>slide list</p>

<table>
<tr>
<th>項目名</th>
<th>実際の値</th>
</tr>
</table>

<br />

<%= link_to 'new request', new_search_path %>

app/views/slides/show.html.erb
<h1>Sides#index</h1>
<p>slide list</p>

<table>
<tr>
<th>requestid</th>
<th>ID</th>
<th>Title</th>
<th>Description</th>
<th>Status</th>
<th>URL</th>
<th>DownloadURL</th>
</tr>
<% @slides.each do |s| %>
<tr>
<th> <%= s.requestid %></th>
<th> <%= s.ID %></th>
<th> <%= s.Title %></th>
<th> <%= s.Description %></th>
<th> <%= s.Status %></th>
<th> <%= s.URL %></th>
<th> <%= s.DownloadURL %></th>
</tr>
<% end %>
</table>

<br />

<%= link_to 'new request', new_search_path %>

app/views/slides/update.html.erb
<h1>Sides#index</h1>
<p>slide list</p>

<table>
<tr>
<th>-</th>
<th>ID</th>
<th>Title</th>
<th>URL</th>
<th>Status</th>
<th>Language</th>
</tr>
<% @slides.each do |s| %>
<tr>
<th> <%= link_to '修正/削除' ,edit_slide_info_path(:ID=>s.ID,:requestid=>s.requestid), :method => :get %> </th>
<th> <%= s.ID %></th>
<th> <%= s.language %></th>
<th> <%= s.Title %></th>
<th> <%= s.URL %></th>
<th> <%= s.Status %></th>
</tr>
<% end %>
</table>

<br />

<%= link_to 'new request', new_search_path %>